### PR TITLE
remove trailing comma to allow build on xcode 16.1

### PR DESCRIPTION
**Pull request by jwoglom**
Swift 6.1 available in Xcode 16.3 allows trailing commas on function calls, but in older swift/xcode versions it is a compile error. This allows Trio to build with Xcode 16.1 on Sequoia.

per https://medium.com/@mi9nxi/swifts-evolution-trailing-commas-in-function-calls-in-xcode-16-3-2947ae5528ef:
> **What Changed in Xcode 16.3:**
> Prior to Xcode 16.3, Swift did not allow trailing commas in function calls. For example, this code would fail to compile:
> ```
> func someFunction(_ input: Int...) {
>     print("input is:", input)
> }
> 
> // This would cause a compilation error in Xcode 16.1 and earlier
> someFunction(1, 2, 3,)
> ```
> However, with Xcode 16.3, the same code builds without any issues. The compiler now accepts the trailing comma after the last parameter in a function call.

### CODE REVIEW

**Comment by dnzxy** [comment]
Sorry, what‘s Xcode 12.1? 
We currently aim for Swift 5 conformity and Xcode 16.4, which can be used up to macOS 26.1.
Starting with macOS 26.2, you can no longer run Xcode 16.4, meaning you are required to run Xcode 26. 
Why is this required for what Trio currently supports?

**Comment by jwoglom** [comment]
> Sorry, what‘s Xcode 12.1? We currently aim for Swift 5 conformity and Xcode 16.4, which can be used up to macOS 26.1. Starting with macOS 26.2, you can no longer run Xcode 16.4, meaning you are required to run Xcode 26. Why is this required for what Trio currently supports?

heya, I typoed the xcode version, I meant xcode 16.1 which I've been using to successfully build trio on my mac with sequoia (macos 15.1) -- I haven't upgraded past that yet. I noticed that the trailing commas were the only issue with the build on this xcode version. i pinged you on discord but you saw the PR first :P

**Comment by jwoglom** [comment]
i'll close this for now
