### PR TITLE
Fix CI Unit Tests

### PR DESCRIPTION
**Pull request by trioneer-dev**
## Summary

Trio dev’s CI unit tests have been failing since #1377 merged (it was merged with both checks already failing). Both jobs fail, for three independent reasons.

Reference run: https://github.com/nightscout/Trio/actions/runs/31322045618

1. Algorithm package no longer compiles. AlgorithmPackage/OpenAPSSwiftTests is a symlink to TrioTests/OpenAPSSwiftTests, so the new Parity/ files joined the SPM test target. They throw TestError, declared in TrioTests/TestError.swift one directory up, outside the symlink: 
* ParityHarness.swift:33:19: error: cannot find 'TestError' in scope
* ParityScenarios.swift:249:19: error: cannot find 'TestError' in scope
* Replaced with a local ParityError. Also excluded Parity/goldens from the target. They are read via #filePath, and SwiftPM warned about 70 undeclared files on every build.

2. Test runner crash from the iobTotal precondition. IobCalculation.prepare now binary-searches the DIA cutoff and asserts its treatments are sorted ascending. IobTotalTests."should ignore future treatments" passes them descending, so both jobs abort mid-run: Trio/IobCalculation.swift:141: Assertion failed: iobTotal treatments must be sorted ascending
Every production caller feeds calcTempTreatments output, which is sorted, so the test input was the wrong side of the contract. Reordered; the test still asserts the future bolus is ignored.

3. Parity goldens only compare on a Europe/Berlin machine. ParityEnv.pinned sets NSTimeZone.default, which moves Calendar.current but not TimeZone.current — and TimeZone.current is what WallClock reads. On the GMT runner the pipeline ran in GMT against goldens recorded in Europe/Berlin: `Expectation failed: (TimeZone.current.identifier → "GMT") == (ParityEnv.timeZoneIdentifier → "Europe/Berlin”)`.
This led to 126 issues in OpenAPSSwift golden parity, 9288 in Wall clock parity. The pin now repoints the process time zone (setenv / tzset / resetSystemTimeZone), which both APIs honour. This was invisible locally because the goldens were authored in the pinned zone.
 
Also: QuickPickTreatmentsTests.swift is rewritten by the SwiftFormat build phase, which CI reports as Uncommitted change detected. This PR commits a linting fix.

### CODE REVIEW

**Review by kingst — APPROVED** [review]
LGTM

**Comment by trioneer-dev** [comment]
@kingst please give this another review. fixed the flakyness of tests (to a point) and increased speed by introducing smart caching and omitting unnecessary operations for unit test builds of the code base.

**Review by kingst — APPROVED** [review]
LGTM
